#!/bin/sh

bspc config border_width         1
bspc config window_gap           80  

bspc config top_padding          0
bspc config left_padding         0   
bspc config right_padding        0   
bspc config bottom_padding       100 

bspc config normal_border_color  \#505050
bspc config active_border_color  \#D3D3D3
bspc config focused_border_color \#D3D3D3
bspc config presel_border_color \#ffffff

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
