#! /bin/sh

#3~/.wmthemelinks/bspwmrc
~/themes/active/bspwmrc

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a tilda floating=on focus=off manage=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a heimdallr-client floating=on

bspc config auto_cancel true

#bspc rule -a xfce4-terminal border_width=10
